source 'https://rubygems.org'


gem 'rails', '4.1.6'
gem 'pg'
gem 'uglifier', '>= 1.3.0'
gem 'tzinfo-data', platforms: [:mingw, :mswin]
gem 'active_model_serializers'

group :development, :test do
  gem 'byebug'
  gem 'rspec-rails', '~> 3.0'
  gem 'shoulda'
  gem 'factory_girl_rails'
  gem 'thin'
end