
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  # place in your db creds here
  username: # some_name
  password: # some_password

development:
  <<: *default
  database: budg_development

test:
  <<: *default
  database: budg_test
